# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e23eaa4d-24df-4d31-8070-20a355727db1";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0E6D-7314";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/backup_images" = {
    device = "//192.168.1.250/backup_images";
    fsType = "cifs";
    options = ["credentials=/etc/samba/cred" "uid=1000" "gid=100"];
  };

  fileSystems."/mnt/roon_data" = {
    device = "//192.168.1.250/roon_data_yakov";
    fsType = "cifs";
    options = ["credentials=/etc/samba/cred" "uid=1000" "gid=100"];
  };

  fileSystems."/mnt/ventoy-iso" = {
    device = "/dev/disk/by-uuid/1C11-749A";
    fsType = "exfat";
    options = ["noauto"];
  };

  fileSystems."/mnt/ventoy-img" = {
    device = "/dev/disk/by-uuid/230bf232-6d96-4e7d-bae2-9144f758d41a";
    fsType = "ext4";
    options = ["noauto"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
